// WARNING: This file was generated by gen/generator.go

package fortigate

// Fake Fortigate Client
type FakeClient struct {
	FirewallAddresss map[string]*FirewallAddress
	FirewallPolicys  map[string]*FirewallPolicy
	VIPs             map[string]*VIP
}

func NewFakeClient() *FakeClient {
	return &FakeClient{
		FirewallAddresss: map[string]*FirewallAddress{},
		FirewallPolicys:  map[string]*FirewallPolicy{},
		VIPs:             map[string]*VIP{},
	}
}
